lib/planning_poker_web/router.ex
defmodule PlanningPokerWeb.Router do
  use PlanningPokerWeb, :router

  pipeline :auth do
    plug(PlanningPoker.Accounts.Pipeline)
    plug(PlanningPoker.CurrentUser)
    plug(PlanningPokerWeb.Context)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(:assign_token)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api" do
    pipe_through([:api, :auth])

    forward("/graphql", Absinthe.Plug, schema: PlanningPokerWeb.Schema)
    forward("/graphiql", Absinthe.Plug.GraphiQL, schema: PlanningPokerWeb.Schema)
  end

  scope "/", PlanningPokerWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    post("/", PageController, :login)
    post("/logout", PageController, :logout)

    resources "/users", UserController do
      get("/user/current", UserController, :current, as: :current_user)
      delete("/logout", AuthController, :delete)
    end
  end

  scope "/", PlanningPokerWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth, :ensure_auth])

    resources "/games", GameController do
      post("/new_round", GameController, :new_round, as: :new_round)
      post("/close_round", GameController, :close_round, as: :close_round)
      post("/join", GameController, :join, as: :join)
      post("/leave", GameController, :leave, as: :leave)
      post("/estimate", GameController, :estimate, as: :estimate)
      put("/estimate", GameController, :estimate, as: :estimate)
    end

    resources("/rounds", RoundController)
    get("/secret", PageController, :secret)
  end

  scope "/api/v1/auth", PlanningPokerWeb do
    pipe_through(:browser)

    # Used in testing
    post("/test_sign_in", AuthController, :test_sign_in_user)

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
  end

  def log(conn, s) do
    IO.puts("---plug #{s}")
    IO.inspect(conn)
    conn
  end

  def assign_token(conn, _) do
    token = PlanningPoker.Guardian.Plug.current_token(conn)

    conn
    |> assign(:user_token, token)
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlanningPokerWeb do
  #   pipe_through :api
  # end
end

lib/planning_poker/games/game.ex
defmodule PlanningPoker.Games.Game do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlanningPoker.Games.{Game}

  schema "games" do
    field(:name, :string)
    field(:status, :string)
    has_many(:rounds, PlanningPoker.Rounds.Round)
    has_many(:game_players, PlanningPoker.Games.GamePlayer)
    many_to_many(:players, PlanningPoker.Accounts.User, join_through: "game_players")

    timestamps()
  end

  def possible_status do
    ["open", "closed"]
  end

  @doc false
  def changeset(%Game{} = game, attrs) do
    game
    |> cast(attrs, [:name, :status])
    |> validate_required([:name, :status])
    |> validate_inclusion(:status, possible_status())
  end
end

lib/planning_poker/games/game_player.ex
defmodule PlanningPoker.Games.GamePlayer do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlanningPoker.Games.{Game, GamePlayer}
  alias PlanningPoker.Accounts.User

  schema "game_players" do
    belongs_to(:user, User)
    belongs_to(:game, Game)

    timestamps()
  end

  @doc false
  def changeset(%GamePlayer{} = player, attrs) do
    player
    |> cast(attrs, [:user_id, :game_id])
    |> validate_required([:user_id, :game_id])
  end
end

lib/planning_poker/games/games.ex
defmodule PlanningPoker.Games do
  @moduledoc """
  The Games context.
  """

  import Ecto.Query, warn: false
  alias PlanningPoker.Repo

  alias PlanningPoker.Accounts.User
  alias PlanningPoker.Games.{Game, GamePlayer}
  alias PlanningPoker.Rounds
  alias PlanningPoker.Rounds.Round

  @doc """
  Returns the list of games.

  ## Examples

      iex> list_games()
      [%Game{}, ...]

  """
  def list_games do
    Repo.all(Game)
  end

  @doc """
  Returns a list of all open games for the given user
  """
  def my_games(user) do
    Ecto.Query.from(
      g in Game,
      join: u in assoc(g, :players),
      where: u.id == ^user.id
    ) |> Repo.all
  end

  @doc """
  Gets a single game.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_game!(123)
      %Game{}

      iex> get_game!(456)
      ** (Ecto.NoResultsError)

  """
  def get_game!(id), do: Repo.get!(Game, id)
  def get_game(id), do: Repo.get(Game, id)

  @doc """
  Creates a game.

  ## Examples

      iex> create_game(%{field: value})
      {:ok, %Game{}}

      iex> create_game(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_game(attrs \\ %{}) do
    %Game{}
    |> Game.changeset(attrs)
    |> Repo.insert()
  end

  def create_game_with_round(attrs \\ %{}) do
    with {:ok, game} <-
           %Game{}
           |> Game.changeset(attrs)
           |> Repo.insert(),
         {:ok, round} <- Rounds.next_round(game.id),
         do: {:ok, game}
  end

  @doc """
  Updates a game.

  ## Examples

      iex> update_game(game, %{field: new_value})
      {:ok, %Game{}}

      iex> update_game(game, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_game(%Game{} = game, attrs) do
    game
    |> Game.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Game.

  ## Examples

      iex> delete_game(game)
      {:ok, %Game{}}

      iex> delete_game(game)
      {:error, %Ecto.Changeset{}}

  """
  def delete_game(%Game{} = game) do
    Repo.delete(game)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking game changes.

  ## Examples

      iex> change_game(game)
      %Ecto.Changeset{source: %Game{}}

  """
  def change_game(%Game{} = game) do
    Game.changeset(game, %{})
  end

  def current_round(game) do
    from(
      r in Ecto.assoc(game, :rounds),
      order_by: [desc: r.inserted_at],
      limit: 1
    )
    |> Repo.one()
  end

  @doc """
  Returns the list of rounds.

  ## Examples

      iex> list_rounds()
      [%Round{}, ...]

  """
  def list_rounds do
    Repo.all(Round)
  end

  @doc """
  Gets a single round.

  Raises `Ecto.NoResultsError` if the Round does not exist.

  ## Examples

      iex> get_round!(123)
      %Round{}

      iex> get_round!(456)
      ** (Ecto.NoResultsError)

  """
  def get_round!(id), do: Repo.get!(Round, id)

  @doc """
  Creates a round.

  ## Examples

      iex> create_round(%{field: value})
      {:ok, %Round{}}

      iex> create_round(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_round(attrs \\ %{}) do
    IO.puts("creating round with attrs")
    IO.inspect(attrs)

    %Round{}
    |> Round.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a round.

  ## Examples

      iex> update_round(round, %{field: new_value})
      {:ok, %Round{}}

      iex> update_round(round, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_round(%Round{} = round, attrs) do
    round
    |> Round.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Round.

  ## Examples

      iex> delete_round(round)
      {:ok, %Round{}}

      iex> delete_round(round)
      {:error, %Ecto.Changeset{}}

  """
  def delete_round(%Round{} = round) do
    Repo.delete(round)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking round changes.

  ## Examples

      iex> change_round(round)
      %Ecto.Changeset{source: %Round{}}

  """
  def change_round(%Round{} = round) do
    Round.changeset(round, %{})
  end

  @spec get_players(%Game{}) :: [%PlanningPoker.Accounts.User{}]
  def get_players(%Game{} = game) do
    game
    |> Ecto.assoc(:players)
    |> Repo.all()
  end

  def get_players(id), do: get_players(Repo.get!(Game, id))

  def join_game(game_id, %User{} = user) do
    Repo.transaction(fn ->
      {:ok, game_player} =
        GamePlayer.changeset(%GamePlayer{}, %{game_id: game_id, user_id: user.id})
        |> Repo.insert()

      round = game_id |> get_game!() |> current_round()
      Rounds.create_pending_estimate(round, game_player)
    end)
  end

  def leave_game(game_id, %User{} = user) do
    Repo.transaction(fn ->
      from(g in GamePlayer, where: [game_id: ^game_id, user_id: ^user.id])
      |> Repo.delete_all()

      # find estimates for all rounds for the user/game
    end)
  end
end

lib/planning_poker/games/round.ex
defmodule PlanningPoker.Games.Round do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlanningPoker.Games.Round


  schema "rounds" do
    field :status, :string
    field :game_id, :id

    timestamps()
  end

  def possible_status do
    ["open", "closed"]
  end

  @doc false
  def changeset(%Round{} = round, attrs) do
    round
    |> cast(attrs, [:game_id, :status])
    |> validate_required([:game_id, :status])
    |> validate_inclusion(:status, possible_status())
  end
end

lib/planning_poker_web/controllers/game_controller.ex
defmodule PlanningPokerWeb.GameController do
  use PlanningPokerWeb, :controller

  alias PlanningPoker.Games
  alias PlanningPoker.Rounds
  alias PlanningPoker.Games.{Game}

  def index(conn, _params) do
    games = Games.list_games()
    render(conn, "index.html", games: games)
  end

  def new(conn, _params) do
    changeset = Games.change_game(%Game{status: "open"})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"game" => game_params}) do
    case Games.create_game_with_round(game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game created successfully.")
        |> redirect(to: game_path(conn, :show, game))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def new_round(conn, %{"game_id" => game_id}) do
    case Rounds.next_round(game_id) do
      {:ok, _round} ->
        refresh_game_page(game_id)

        conn
        |> put_flash(:info, "Round created successfully.")
        |> redirect(to: game_path(conn, :show, game_id))

      {:error, %Ecto.Changeset{}} ->
        conn
        |> redirect(to: game_path(conn, :show, game_id))
    end
  end

  def close_round(conn, %{"game_id" => game_id}) do
    round = Games.current_round(Games.get_game!(game_id))

    case Rounds.close_round(round) do
      {:ok, _round} ->
        refresh_game_page(game_id)

        conn
        |> put_flash(:info, "Round closed!")
        |> redirect(to: game_path(conn, :show, game_id))

      {:error, %Ecto.Changeset{} = _changeset} ->
        conn
        |> put_flash(:error, "There was a problem closing the round")
        |> redirect(to: game_path(conn, :show, game_id))
    end
  end

  def join(conn, %{"game_id" => game_id}) do
    current_user = Guardian.Plug.current_resource(conn)

    case Games.join_game(game_id, current_user) do
      {:ok, _player} ->
        refresh_game_page(game_id)

        conn
        |> put_flash(:info, "You have joined the game")
        |> redirect(to: game_path(conn, :show, game_id))

      {:error, error_msg} ->
        conn
        |> put_flash(:error, error_msg)
        |> redirect(to: game_path(conn, :show, game_id))
    end
  end

  defp refresh_game_page(game_id) do
    game = Games.get_game!(game_id)
    current_round = Games.current_round(game)
    players = Games.get_players(game)

    refresh_estimates(game_id, current_round, players)
  end

  defp refresh_estimates(game_id, round, _players) do
    Task.async(fn ->
      payload = %{
          estimates: Rounds.estimates(round),
          round: round
      }
      PlanningPokerWeb.Endpoint.broadcast!("game:" <> game_id, "estimates_updated", payload)
    end)
  end

  def leave(conn, %{"game_id" => game_id}) do
    current_user = Guardian.Plug.current_resource(conn)

    case Games.leave_game(game_id, current_user) do
      {:ok, _player} ->
        refresh_game_page(game_id)

        conn
        |> put_flash(:info, "You have joined the game")
        |> redirect(to: game_path(conn, :show, game_id))

      {:error, error_msg} ->
        conn
        |> put_flash(:error, error_msg)
        |> redirect(to: game_path(conn, :show, game_id))
    end
  end

  def show(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    current_round = Games.current_round(game)
    players = Games.get_players(game)
    current_user = Guardian.Plug.current_resource(conn)

    my_estimate =
      case Rounds.current_estimate(current_round, current_user) do
        nil -> nil
        e -> Ecto.Changeset.change(e)
      end

    render(
      conn,
      "show.html",
      game: game,
      current_round: current_round,
      players: players,
      current_user: current_user,
      estimates: Rounds.estimates(current_round),
      my_estimate: my_estimate
    )
  end

  def estimate(conn, %{
        "game_id" => game_id,
        "estimate" => %{"amount" => amount, "round_id" => round_id}
      }) do
    current_user = Guardian.Plug.current_resource(conn)
    round = Rounds.get_round!(round_id)
    game = Games.get_game!(game_id)
    _players = Games.get_players(game)

    case Rounds.set_estimate(round, current_user, amount) do
      {:ok, _estimate} ->
        refresh_game_page(game_id)

        conn
        |> redirect(to: game_path(conn, :show, game_id))

      {:error, _} ->
        conn
        |> redirect(to: game_path(conn, :show, game_id))
    end
  end

  def edit(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    changeset = Games.change_game(game)

    conn
    |> put_flash(:info, "You have joined the game")

    render(conn, "edit.html", game: game, changeset: changeset)
  end

  def update(conn, %{"id" => id, "game" => game_params}) do
    game = Games.get_game!(id)

    case Games.update_game(game, game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game updated successfully.")
        |> redirect(to: game_path(conn, :show, game))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", game: game, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    {:ok, _game} = Games.delete_game(game)

    conn
    |> put_flash(:info, "Game deleted successfully.")
    |> redirect(to: game_path(conn, :index))
  end
end

lib/planning_poker_web/views/game_view.ex
defmodule PlanningPokerWeb.GameView do
  use PlanningPokerWeb, :view
  alias PlanningPoker.Rounds.{Estimate,Round}

  def vote_string(%Round{status: status}, %{email: current_user_email}, %Estimate{} = estimate) do
    email = estimate.user.email
    pending = Estimate.pending?(estimate)

    current_user? = email == current_user_email

    if current_user? do
      vote = case {status, pending} do
        {"closed", true} -> "did not vote"
        {"open", true} -> "has not voted"
        {_, false} -> "voted #{estimate.amount}"
      end
      [email, "(you)", " ", vote]
    else
      vote = case {status, pending} do
        {"closed", true} -> "did not vote"
        {"closed", false} -> "voted #{estimate.amount}"
        {"open", true} -> "has not voted"
        {"open", false} -> "has voted"
      end
      [email, " ", vote]
    end
  end
end

lib/planning_poker_web/templates/game/edit.html.eex
<h2>Edit Game</h2>

<%= render "form.html", Map.put(assigns, :action, game_path(@conn, :update, @game)) %>

<span><%= link "Back", to: game_path(@conn, :index) %></span>

lib/planning_poker_web/templates/game/estimates.html.eex
<ul>
  <%= for estimate <- @estimates do %>
    <li class="<%= if(Estimate.pending?(estimate), do: "estimate tag is-light", else: "estimate tag is-success")%>">
      <%= vote_string(@round, @current_user, estimate) %>
    </li>
  <% end %>
</ul>

lib/planning_poker_web/templates/game/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= text_input f, :status, class: "form-control" %>
    <%= error_tag f, :status %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/planning_poker_web/templates/game/index.html.eex
<h2>Listing Games</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for game <- @games do %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.status %></td>

      <td class="text-right">
        <span><%= link "Show", to: game_path(@conn, :show, game), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: game_path(@conn, :edit, game), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: game_path(@conn, :delete, game), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Game", to: game_path(@conn, :new) %></span>

lib/planning_poker_web/templates/game/new.html.eex
<h2>New Game</h2>

<%= render "form.html", Map.put(assigns, :action, game_path(@conn, :create)) %>

<span><%= link "Back", to: game_path(@conn, :index) %></span>

lib/planning_poker_web/templates/game/show.html.eex
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <div>
        <h1 class="title is-spaced">
          <%= @game.name %>
        </h1>
        <h3 class="subtitle">
            (<%= @game.status %>)
        </h3>
      </div>
    </div>
    <div class="level-item">
      <div class="column">
        <%= if Enum.member?(@players, @current_user) do %>
          <span><%= link "Leave Game", to: game_leave_path(@conn, :leave, @game), method: :post %></span>
        <% else %>
          <span><%= link "Join Game", to: game_join_path(@conn, :join, @game), method: :post %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= if @current_round == nil || @current_round.status == "closed" do %>
  <p>
    <%= link "Start new round", to: game_new_round_path(@conn, :new_round, @game), method: :post %>
  </p>
<% end %>

<%= if @current_round do %>
  <div class="level">
    <div class="level-left">
      <h1 class="title is-4" data-round-name>
        Round <%= @current_round.id %>
      </h1>
    </div>
    <div class="level-right">
      <div class="level-item">
        <%= if @current_round.status == "open" do %>
          <span><%= link "Close Round", to: game_close_round_path(@conn, :close_round, @game), method: :post %></span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <div id="estimates"
          data-controller="estimates"
          data-game-id=<%= @game.id %>>
        <%= render "estimates.html", players: @players, estimates: @estimates, round: @current_round, current_user: @current_user %>
      </div>
    </div>
    <div class="column">
      <%= if Enum.member?(@players, @current_user) && @current_round.status == "open" do %>
        <%= form_for @my_estimate, game_estimate_path(@conn, :estimate, @game), fn f -> %>
          <%= hidden_input f, :round_id %>
          <div class="field">
            <label for="" class="label">My Estimate</label>
            <div class="select">
              <%= select f, :amount, ~w(1 2 3 5 8 13 pass) %>
            </div>
          </div>
          <div class="field">
            <%= submit "Submit", class: "button is-primary" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<span><%= link "Edit", to: game_path(@conn, :edit, @game) %></span>
<span><%= link "Back", to: game_path(@conn, :index) %></span>